<?php
// pumping-system-maintenance - AUTO-GENERATED by Phase 8
$page_title = "صيانة أنظمة الضخ - عقود سنوية | روائع الكريستال";
$base_path = "../";
$active_page = "blog";

include '../includes/config.php';
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- SEO Meta Tags -->
    <title><?= $page_title ?> | روائع الكريستال</title>
    <meta name="description"
        content="صيانة شاملة لأنظمة ضخ المياه. عقود صيانة دورية ووقائية. فريق فني متخصص. اتصل 0550698111">
    <meta name="keywords" content="صيانة أنظمة الضخ, مضخات مياه, لوحات تحكم, السعودية">
    <meta name="robots" content="index, follow">

    <!-- Canonical -->
    <link rel="canonical" href="https://brilliantserv.com/blog/pumping-system-maintenance.html">

    <!-- Open Graph -->
    <meta property="og:type" content="article">
    <meta property="og:title" content="<?= $page_title ?>">
    <meta property="og:description"
        content="صيانة شاملة لأنظمة ضخ المياه. عقود صيانة دورية ووقائية. فريق فني متخصص. اتصل 0550698111">
    <meta property="og:url" content="https://brilliantserv.com/blog/pumping-system-maintenance.html">
    <meta property="og:image" content="https://brilliantserv.com/media/blog/pumping-system-maintenance-featured.webp">

    <!-- JSON-LD Article Schema -->
    <script type="application/ld+json">
    {
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": "<?= $page_title ?>",
        "datePublished": "2026-02-01",
        "dateModified": "2026-02-01",
        "author": {"@type": "Organization", "name": "مؤسسة روائع الكريستال"},
        "publisher": {
            "@type": "Organization",
            "name": "مؤسسة روائع الكريستال",
            "logo": {"@type": "ImageObject", "url": "https://brilliantserv.com/media/logo.webp"}
        }
    }
    </script>

    <?php include '../includes/head.php'; ?>
</head>

<body>
    <?php include '../includes/nav.php'; ?>

    <section class="page-hero">
        <div class="container">
            <div class="page-hero-content">
                <span class="section-badge">الخدمات الفنية</span>
                <h1>صيانة أنظمة الضخ</h1>
                <p>آخر تحديث: 1 فبراير 2026</p>
            </div>
        </div>
    </section>

    <article class="blog-article">
        <div class="container">
            <div class="article-wrapper">
                <div class="article-image">
                    <img src="../media/blog/pumping-system-maintenance-featured.webp"
                        alt="صيانة أنظمة الضخ - روائع الكريستال" loading="lazy">
                </div>
                <div class="article-body">
                    <!-- المحتوى الرئيسي -->
                    <h2 id="section-1">ما هي خدمة صيانة أنظمة الضخ؟</h2>
                    <p>نقدم خدمات صيانة شاملة لأنظمة ضخ المياه. تشمل الصيانة الوقائية والدورية والإصلاحات العاجلة. نقدم
                        عقود صيانة سنوية تضمن عمل الأنظمة بكفاءة عالية على مدار العام.</p>
                    <!-- Article Meta -->
                    <div class="article-meta">
                        <img src="../media/team/engineer-avatar.webp" alt="فريق روائع الكريستال" class="author-avatar" onerror="this.style.display='none'">
                        <div class="meta-info">
                            <span class="author-name">فريق روائع الكريستال الهندسي</span>
                            <div class="meta-details">
                                <span class="article-date">آخر تحديث: <?= date('j F Y', filemtime(__FILE__)) ?></span>
                                <span class="reading-time">⏱️ <?= ceil(str_word_count(strip_tags(file_get_contents(__FILE__))) / 200) ?> دقائق قراءة</span>
                            </div>
                        </div>
                    </div>

                    <!-- Stats Grid -->
                    <div class="article-stats-grid">
                        <div class="stat-card">
                            <span class="stat-number">7+</span>
                            <span class="stat-label">أنواع مضخات</span>
                        </div>
                        <div class="stat-card">
                            <span class="stat-number">500+</span>
                            <span class="stat-label">مشروع منجز</span>
                        </div>
                        <div class="stat-card">
                            <span class="stat-number">15+</span>
                            <span class="stat-label">سنة خبرة</span>
                        </div>
                        <div class="stat-card">
                            <span class="stat-number">24/7</span>
                            <span class="stat-label">دعم فني</span>
                        </div>
                    </div>

                    <!-- Table of Contents -->
                    <div class="article-toc">
                        <h4>📋 محتويات المقال</h4>
                        <ol>
                            <li><a href="#section-1">1. ما هي خدمة صيانة أنظمة الضخ؟</a></li>
                            <li><a href="#section-2">2. مميزات خدماتنا</a></li>
                            <li><a href="#section-3">3. أنواع العقود المتوفرة</a></li>
                        </ol>
                    </div>


                    <h2 id="section-2">مميزات خدماتنا</h2>
                    <ul>
                        <li>فحص دوري شامل للأنظمة</li>
                        <li>صيانة وقائية للمضخات واللوحات</li>
                        <li>استبدال قطع الغيار التالفة</li>
                        <li>تقارير دورية عن حالة الأنظمة</li>
                    </ul>

                    <h2 id="section-3">أنواع العقود المتوفرة</h2>
                    <ul>
                        <li>عقود صيانة شاملة</li>
                        <li>عقود صيانة جزئية</li>
                        <li>عقود صيانة طارئة</li>
                        <li>عقود زيارات دورية</li>
                    </ul>

                    <!-- CTA Box -->
                    <?php 
                    // Article data for CTA
                    $article = ['title' => $page_title];
                    
                    // Related articles
                    $related_articles = [
                        'pump-maintenance-contracts.php' => 'عقود صيانة مضخات',
                        'pumping-system-installation.php' => 'تركيب أنظمة ضخ'
                    ];
                    
                    include '../includes/blog-article-footer.php';
                    ?>
