<?php
// pump-supplier-saudi - AUTO-GENERATED by Phase 8
$page_title = "مورد مضخات مياه في السعودية | روائع الكريستال";
$base_path = "../";
$active_page = "blog";

include '../includes/config.php';
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- SEO Meta Tags -->
    <title><?= $page_title ?> | روائع الكريستال</title>
    <meta name="description"
        content="نورد مضخات المياه لجميع مناطق المملكة. ماركات عالمية، أسعار تنافسية، ضمان شامل. اتصل 0550698111">
    <meta name="keywords" content="مورد مضخات, مضخات مياه, لوحات تحكم, السعودية">
    <meta name="robots" content="index, follow">

    <!-- Canonical -->
    <link rel="canonical" href="https://brilliantserv.com/blog/pump-supplier-saudi.html">

    <!-- Open Graph -->
    <meta property="og:type" content="article">
    <meta property="og:title" content="<?= $page_title ?>">
    <meta property="og:description"
        content="نورد مضخات المياه لجميع مناطق المملكة. ماركات عالمية، أسعار تنافسية، ضمان شامل. اتصل 0550698111">
    <meta property="og:url" content="https://brilliantserv.com/blog/pump-supplier-saudi.html">
    <meta property="og:image" content="https://brilliantserv.com/media/blog/pump-supplier-saudi-featured.webp">

    <!-- JSON-LD Article Schema -->
    <script type="application/ld+json">
    {
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": "<?= $page_title ?>",
        "datePublished": "2026-02-01",
        "dateModified": "2026-02-01",
        "author": {"@type": "Organization", "name": "مؤسسة روائع الكريستال"},
        "publisher": {
            "@type": "Organization",
            "name": "مؤسسة روائع الكريستال",
            "logo": {"@type": "ImageObject", "url": "https://brilliantserv.com/media/logo.webp"}
        }
    }
    </script>

    <?php include '../includes/head.php'; ?>
</head>

<body>
    <?php include '../includes/nav.php'; ?>

    <section class="page-hero">
        <div class="container">
            <div class="page-hero-content">
                <span class="section-badge">مضخات المياه</span>
                <h1>مورد مضخات مياه السعودية</h1>
                <p>آخر تحديث: 1 فبراير 2026</p>
            </div>
        </div>
    </section>

    <article class="blog-article">
        <div class="container">
            <div class="article-wrapper">
                <div class="article-image">
                    <img src="../media/blog/pump-supplier-saudi-featured.webp"
                        alt="مورد مضخات السعودية - روائع الكريستال" loading="lazy">
                </div>
                <div class="article-body">
                    <!-- المحتوى الرئيسي -->
                    <h2 id="section-1">ما هي خدمة مورد مضخات السعودية؟</h2>
                    <p>نحن مورد رئيسي لمضخات المياه في المملكة العربية السعودية. نقدم خدمات التوريد لجميع مناطق المملكة
                        مع خدمات التركيب والصيانة. نتعامل مع أفضل الماركات العالمية ونضمن أفضل الأسعار والجودة.</p>
                    <!-- Article Meta -->
                    <div class="article-meta">
                        <img src="../media/team/engineer-avatar.webp" alt="فريق روائع الكريستال" class="author-avatar" onerror="this.style.display='none'">
                        <div class="meta-info">
                            <span class="author-name">فريق روائع الكريستال الهندسي</span>
                            <div class="meta-details">
                                <span class="article-date">آخر تحديث: <?= date('j F Y', filemtime(__FILE__)) ?></span>
                                <span class="reading-time">⏱️ <?= ceil(str_word_count(strip_tags(file_get_contents(__FILE__))) / 200) ?> دقائق قراءة</span>
                            </div>
                        </div>
                    </div>

                    <!-- Stats Grid -->
                    <div class="article-stats-grid">
                        <div class="stat-card">
                            <span class="stat-number">7+</span>
                            <span class="stat-label">أنواع مضخات</span>
                        </div>
                        <div class="stat-card">
                            <span class="stat-number">500+</span>
                            <span class="stat-label">مشروع منجز</span>
                        </div>
                        <div class="stat-card">
                            <span class="stat-number">15+</span>
                            <span class="stat-label">سنة خبرة</span>
                        </div>
                        <div class="stat-card">
                            <span class="stat-number">24/7</span>
                            <span class="stat-label">دعم فني</span>
                        </div>
                    </div>

                    <!-- Table of Contents -->
                    <div class="article-toc">
                        <h4>📋 محتويات المقال</h4>
                        <ol>
                            <li><a href="#section-1">1. ما هي خدمة مورد مضخات السعودية؟</a></li>
                            <li><a href="#section-2">2. مميزات خدماتنا</a></li>
                            <li><a href="#section-3">3. العلامات التجارية المدعومة</a></li>
                        </ol>
                    </div>


                    <h2 id="section-2">مميزات خدماتنا</h2>
                    <ul>
                        <li>قطع غيار أصلية من الشركات المصنعة</li>
                        <li>ضمان شامل على جميع الأعمال</li>
                        <li>فريق فني متخصص ذو خبرة عالية</li>
                        <li>خدمة سريعة في الرياض والمنطقة الوسطى</li>
                    </ul>

                    <h2 id="section-3">العلامات التجارية المدعومة</h2>
                    <ul>
                        <li>Grundfos (جراندفوس)</li>
                        <li>Lowara (لووارا)</li>
                        <li>KSB</li>
                        <li>Ebara (إبارا)</li>
                    </ul>

                    <!-- CTA Box -->
                    <?php 
                    // Article data for CTA
                    $article = ['title' => $page_title];
                    
                    // Related articles
                    $related_articles = [
                        'authorized-pump-distributor.php' => 'موزع مضخات معتمد',
                        'water-pumps-saudi.php' => 'مضخات مياه في السعودية'
                    ];
                    
                    include '../includes/blog-article-footer.php';
                    ?>
