<?php
// soft-starter-panels - AUTO-GENERATED by Phase 8
$page_title = "لوحات سوفت ستارتر - تشغيل ناعم | روائع الكريستال";
$base_path = "../";
$active_page = "blog";

include '../includes/config.php';
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- SEO Meta Tags -->
    <title><?= $page_title ?> | روائع الكريستال</title>
    <meta name="description"
        content="لوحات Soft Starter للتشغيل التدريجي للمحركات. تقليل تيار البدء وحماية المحركات. اتصل 0550698111">
    <meta name="keywords" content="لوحات سوفت ستارتر, مضخات مياه, لوحات تحكم, السعودية">
    <meta name="robots" content="index, follow">

    <!-- Canonical -->
    <link rel="canonical" href="https://brilliantserv.com/blog/soft-starter-panels.html">

    <!-- Open Graph -->
    <meta property="og:type" content="article">
    <meta property="og:title" content="<?= $page_title ?>">
    <meta property="og:description"
        content="لوحات Soft Starter للتشغيل التدريجي للمحركات. تقليل تيار البدء وحماية المحركات. اتصل 0550698111">
    <meta property="og:url" content="https://brilliantserv.com/blog/soft-starter-panels.html">
    <meta property="og:image" content="https://brilliantserv.com/media/blog/soft-starter-panels-featured.webp">

    <!-- JSON-LD Article Schema -->
    <script type="application/ld+json">
    {
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": "<?= $page_title ?>",
        "datePublished": "2026-02-01",
        "dateModified": "2026-02-01",
        "author": {"@type": "Organization", "name": "مؤسسة روائع الكريستال"},
        "publisher": {
            "@type": "Organization",
            "name": "مؤسسة روائع الكريستال",
            "logo": {"@type": "ImageObject", "url": "https://brilliantserv.com/media/logo.webp"}
        }
    }
    </script>

    <?php include '../includes/head.php'; ?>
</head>

<body>
    <?php include '../includes/nav.php'; ?>

    <section class="page-hero">
        <div class="container">
            <div class="page-hero-content">
                <span class="section-badge">لوحات التحكم</span>
                <h1>لوحات سوفت ستارتر</h1>
                <p>آخر تحديث: 1 فبراير 2026</p>
            </div>
        </div>
    </section>

    <article class="blog-article">
        <div class="container">
            <div class="article-wrapper">
                <div class="article-image">
                    <img src="../media/blog/soft-starter-panels-featured.webp" alt="لوحات سوفت ستارتر - روائع الكريستال"
                        loading="lazy">
                </div>
                <div class="article-body">
                    <!-- المحتوى الرئيسي -->
                    <h2>ما هي خدمة لوحات سوفت ستارتر؟</h2>
                    <p>لوحات Soft Starter هي أنظمة تحكم تتيح تشغيل المحركات بشكل تدريجي لتقليل تيار البدء العالي. تحمي
                        المحركات من الصدمات الميكانيكية والكهربائية وتطيل عمرها الافتراضي.</p>

                    <h2>مميزات خدماتنا</h2>
                    <ul>
                        <li>تصنيع محلي بمعايير عالمية</li>
                        <li>مكونات أصلية من Schneider وABB</li>
                        <li>برمجة وحماية كاملة للمحركات</li>
                        <li>ضمان شامل على جميع اللوحات</li>
                    </ul>

                    <h2>أنواع اللوحات المتوفرة</h2>
                    <ul>
                        <li>لوحات VFD - تحكم بالسرعة</li>
                        <li>لوحات Star-Delta - تشغيل ناعم</li>
                        <li>لوحات Direct - تشغيل مباشر</li>
                        <li>لوحات Soft Starter - حماية المحرك</li>
                    </ul>

                    <!-- CTA Box -->
                    <div class="article-cta">
                        <h3>تحتاج لوحة سوفت ستارتر؟</h3>
                        <p>فريقنا المتخصص جاهز لخدمتك على مدار الساعة.</p>
                        <div class="cta-buttons">
                            <a href="tel:0550698111" class="btn btn-primary">📞 0550698111</a>
                            <a href="https://wa.me/966550698111" class="btn btn-success">💬 واتساب</a>
                        </div>
                    </div>

                    <!-- Related Articles -->
                    <div class="related-articles">
                        <h3>مقالات ذات صلة</h3>
                        <ul>
                            <li><a href="vfd-programming-pumps.php">برمجة انفرتر VFD</a></li>
                            <li><a href="automatic-control-panels.php">لوحات تحكم أوتوماتيك</a></li>
                        </ul>
                    </div>

                    
                    <?php 
                    // Article data for CTA
                    $article = ['title' => $page_title];
                    
                    // Related articles
                    $related_articles = [
                        'vfd-programming-pumps.php' => 'برمجة انفرتر VFD',
                        'automatic-control-panels.php' => 'لوحات تحكم أوتوماتيك'
                    ];
                    
                    include '../includes/blog-article-footer.php';
                    ?>
